### ISSUE TITLE
Main script should be repo name

### ISSUE THREAD

**Issue by paviro** [Bangee44/MMM-swisstransport#1]
Your mainscript `swisstransport.js` should have the same name your repo has, because the two names have to match. If people clone the project the folder will be called `MMM-swisstransport` if that name is added to the config MM will not find the main script, if you add the name of the mainscript it will not find the module folder.

**Comment by Bangee44** [comment]
Ok, I've updated the files and renamed it.

**Comment by paviro** [comment]
Great!
