### ISSUE TITLE
Can`t find my Trainstation ID

### ISSUE THREAD

**Issue by SquirrelBNCT** [Bangee44/MMM-swisstransport#2]
Hey, i can`t find my Trainstation ID. I used your link and searched my Trainstation that works. But how can i show my ID. It always shows me the ID for Lausanne...

**Comment by Bangee44** [comment]
You need to search it and use Firebug i.e. to check the sourcecode. There you can see your station ID.
Or let me know the one you would like to find.

**Comment by SquirrelBNCT** [comment]
I search for Biel, Mösliacker.

edit: In the Source Code it shows me only the ID for Lausanne..

**Comment by Bangee44** [comment]
008593356

**Comment by SquirrelBNCT** [comment]
Yeah! Great that works! Thank you very much!
